#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/cata/neuron/nrn/nrn-7.6"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/cata/neuron/nrn/nrn-7.6/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/cata/nao_ws/src/rat_model/scripts/x86_64/.libs/libnrnmech.so" "$@"
